name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: python -m pip install .

    - name: Deploy documentation on GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "docs/_build/html"
